import { CnfMaestro } from "../cnf-maestro/cnf-maestro.model";
import { CnfFormaPago } from "../cnf-forma-pago/cnf-forma-pago.model";
import { CnfMoneda } from "../cnf-moneda/cnf-moneda.model";
import { CnfLocal } from "../cnf-local/cnf-local.model";
import { CnfTipoComprobante } from "../cnf-tipo-comprobante/cnf-tipo-comprobante.model";
import { InvAlmacen } from "../inv-almacen/inv-almacen.model";
import { ActComprobanteDetalle } from "../act-comprobante-detalle/act-comprobante-detalle.model";
import * as dayjs from 'dayjs';

export class ActComprobante {
	id: int = "";
	fecha?: dayjs.Dayjs;
	serie: string = "";
	numero: string = "";
	fechaRegistro!: localdatetime;
	billete!: number;
	total!: number;
	vuelto!: number;
	descuento!: number;
	subtotal!: number;
	igv!: number;
	observacion: string = "";
	flagEstado: string = "";
	flagIsventa: string = "";
	envioPseFlag: string = "";
	envioPseMensaje: string = "";
	xmlhash: string = "";
	codigoqr: string = "";
	numTicket: string = "";
	actComprobante!: ActComprobante;
	cnfMaestro: CnfMaestro = new CnfMaestro();
	cnfFormaPago: CnfFormaPago = new CnfFormaPago();
	cnfMoneda: CnfMoneda = new CnfMoneda();
	cnfLocal: CnfLocal = new CnfLocal();
	cnfTipoComprobante: CnfTipoComprobante = new CnfTipoComprobante();
	invAlmacen: InvAlmacen = new InvAlmacen();
	listActComprobanteDetalle: ActComprobanteDetalle[] = [];
	token?: string = "";
};
